import Head from "next/head";

export default function Home() {
  return (
    <div className={`container`}>
      <Head>
        <title>BlogHub</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={`mt-5`}>
        <h1 className={`display-4 my-3`}>
          Welcome to Andro BLOG<span>HUB</span>
        </h1>
        <p className="p-3">
          A blog (a truncation of "weblog") is a discussion or informational
          website published on the World Wide Web consisting of discrete, often
          informal diary-style text entries (posts). Posts are typically
          displayed in reverse chronological order so that the most recent post
          appears first, at the top of the web page.
        </p>
        <hr />

        <div>
          <h2 className="my-4 display-6">Latest Blogs</h2>

          <div className="my-3">
            <h3>React vs Next</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt, aut
              veniam earum quasi officia iste corrupti optio. Corporis
              laboriosam quasi reprehenderit beatae, cumque perferendis pariatur
              nostrum rerum explicabo quam soluta.
            </p>
            <button className="btn btn-dark">view more</button>
          </div>
          <div className="my-3">
            <h3>React vs Next</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt, aut
              veniam earum quasi officia iste corrupti optio. Corporis
              laboriosam quasi reprehenderit beatae, cumque perferendis pariatur
              nostrum rerum explicabo quam soluta.
            </p>
            <button className="btn btn-dark">view more</button>
          </div>
          <div className="my-3">
            <h3>React vs Next</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt, aut
              veniam earum quasi officia iste corrupti optio. Corporis
              laboriosam quasi reprehenderit beatae, cumque perferendis pariatur
              nostrum rerum explicabo quam soluta.
            </p>
            <button className="btn btn-dark">view more</button>
          </div>
        </div>
      </main>
    </div>
  );
}
